### ISSUE TITLE
i915-sriov-dkms default conf changed

### ISSUE THREAD

**Issue by rexpark** [Upinel/PVE-Intel-vGPU#1]
The dkms.conf in step 2 has changed so your sed commands no longer work.

https://github.com/strongtz/i915-sriov-dkms/pull/178/files#diff-0e704add732cacd94a47f89713f52fa8fc38221c218c27e0c90b3a6820d1c263

The default values are now
```
PACKAGE_NAME="i915-sriov-dkms"
PACKAGE_VERSION="2024.07.17"
```

instead of 

```
PACKAGE_NAME="@_PKGBASE@"
PACKAGE_VERSION="@PKGVER@"
```

**Comment by Upinel** [comment]
Thanks!
