### ISSUE TITLE
HDMI pass-through

### ISSUE THREAD

**Issue by zelo66** [Upinel/PVE-Intel-vGPU#2]
Thank you very much for your tutorial. Everything works great. However, I have a question: Is it possible to somehow transmit the signal from the VM to the HDMI port instead of proxmox?

**Comment by Upinel** [comment]
For vGPU, it can't unfortunately, since SR-IOV is splitting resources to multiple vGPUs, there is no longer possible to pass display signal to the physical HDMI port from many vGPUs.
You might need to look for PCIe passthrough, but it’s only possible attached to one VM.
