### ISSUE TITLE
Driver Error 43 in Windows 10 

### ISSUE THREAD

**Issue by Butter2222** [Upinel/PVE-Intel-vGPU#5]
Was able to get the vgpu working and followed the guide to a tee. Adding one of the vgpu's to the vm was successful but the igpu in the vm has a error 43. No idea how im going to solve it since every solution is to fix a regular igpu and not a vgpu. I am using a i5-12600k with its UHD 760 GPU.  Yes I installed the driver using the Intel Arc and another Intel driver app. 

Windows 10 VM Config Below 
agent: 1
args: -cpu host,-hypervisor,kvm=off
bios: ovmf
boot: order=scsi0;ide0;net0
cores: 2
cpu: x86-64-v2-AES
efidisk0: local-lvm:vm-103-disk-0,efitype=4m,pre-enrolled-keys=1,size=4M
hostpci0: 0000:00:02.2,pcie=1
ide0: local:iso/virtio-win.iso,media=cdrom,size=708140K
machine: pc-q35-9.0
memory: 4096
meta: creation-qemu=9.0.2,ctime=1724689654
name: TestVM4Template
net0: e1000=BC:24:11:A3:D2:FE,bridge=vmbr0,firewall=1
numa: 0
ostype: win11
scsi0: local-lvm:vm-103-disk-1,backup=0,cache=writeback,discard=on,size=64G,ssd=1
scsihw: virtio-scsi-pci
smbios1: uuid=76414a45-cbeb-4f8d-b0a6-990e44907eec
sockets: 1
vga: none
vmgenid: 0fae79f4-edd9-4f49-8baa-5fb5691314e7

**Comment by Butter2222** [comment]
Did some messing around and got the error 43 removed but the IGPU does not show it is in use. Maybe parsec disables it? Checked task manager and Intel Arc Center but both dont show any details relating to the IGPU.

**Comment by Butter2222** [comment]
fixed following this guide. Works now on windows 10 and 11. 
https://www.derekseaman.com/2024/07/proxmox-ve-8-2-windows-11-vgpu-vt-d-passthrough-with-intel-alder-lake.html

**Comment by Das5656** [comment]
@Butter2222 
What exactly did you do from that guide to get rid of error 43?
Or did you follow the guide from scratch?

**Comment by Butter2222** [comment]
> @Butter2222 
> What exactly did you do from that guide to get rid of error 43?
> Or did you follow the guide from scratch?

I don't remember. But I think I had to install an older version of the intel driver.
